### ISSUE TITLE
[MOD PROPOSAL] Specifying RSH options for borg ( ssh port / ciphers etc )

### ISSUE THREAD

**Issue by sertys3** [laur89/docker-borg-mysql-backup#14]
Greetings,
thank you for the great work thus far on the scripting side of this project. I have deployed the image as part of a docker-compose with some trial and error and had it running. Yet my borg server uses a non-standart port for SSH which requires either specifying ssh options in the --rsh argument to borg( --rsh 'ssh -oPort=2222') or as an environment variable BORG_RSH in the session. Alternatively one may use the borg uri syntax for setting the host as ssh://my.borg.host:2222/repo/path. All three vectors failed for me because of :
1. argument escaping when trying to pass --rsh with COMMON_OPTS or CREATE_OPTS
2. variable overwriting in /scripts_common.sh when setting BORG_RSH in the container environment
3. adding an extra ':' in the repo string after the port number - becomes ssh://my.borg.host:2222:/repo/path::archive which is invalid

All of these are easily solvable with simple code modification but since this is not a very active project i'm presenting my hacky way of injecting the proper rsh string : 
Specify a container variable in the docker-compose.yml ( or in the run command with -e)
```
environment:
  BORG_RSH: 'ssh -i /root/.ssh/id_rsa -c aes128-ctr -oPort=2222 -oCompression=no -oBatchMode=yes'

```
Set a command argument to the service which becomes the entrypoint:
```
command: bash -c "echo 'Replacing obsolete envars' ; sed -i 's/BORG_RSH/DUMMY/g; s/BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK/DUMMY/g' /scripts_common.sh ; echo 'Done.' ; /usr/local/sbin/entry.sh"
```
I have also removed the BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK var for unattended runs.

This is less than ideal but may help someone in the same position.

Kindest regards,
Daniel

**Comment by laur89** [comment]
> but since this is not a very active project

Since it's feature complete for my use-case :) But problems/different use-cases/discussions are always welcome. I'll be using this image for the foreseeable.

> argument escaping when trying to pass --rsh with COMMON_OPTS or CREATE_OPTS

Ye that's problematic one, as value token contains spaces and we break on spaces. Unless we really need this, I wouldn't bother going for it. Supporting additional values for BORG_RSH makes more sense (see next point)

> variable overwriting in /scripts_common.sh when setting BORG_RSH in the container environment

Excellent point - we shouldn't forcefully set it like so. I'll likely add `RSH_OPTS` and/or `RSH_EXTRA_OPTS` env var to allow overwriting/adding to it.

> adding an extra ':' in the repo string after the port number - becomes ssh://my.borg.host:2222:/repo/path::archive which is invalid

Also good point. Feel like introducing `PORT` env var or similar would be too much as it'll be defined via `REMOTE` anyway. Think adding validation to skip adding the extra `:` in case port is already defined in the value.

> I have also removed the BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK var for unattended runs.

I'll allow overwriting the two BORG env vars we default to `no` at the moment. Note _removing_ these env vars make no sense for unattended scripts as explained in the [docs](https://borgbackup.readthedocs.io/en/stable/deployment/automated-local.html).

> -i /root/.ssh/id_rsa

Note this option is not needed as the that's already the default location where key is picked up from.

> -oPort=2222

~~Would avoid setting port via RSH opts, as that would break the logic [adding remote to ssh/known_hosts](https://github.com/laur89/docker-borg-mysql-backup/blob/65916fed5cdc79f1ce8d58d9d118072d1d961764/scripts/scripts_common.sh#L403-L420). As mentioned above, `REMOTE` env var will soon allow `:PORT` postfix.~~
Not applicable anymore, as said logic has been replaced by `-o StrictHostKeyChecking=no` ssh option.

**Comment by laur89** [comment]
@sertys3 `latest` image now contains following changes:
- `REMOTE` allows ":port" postfix
- `BORG_RSH` can now be provided that _overwrites_ the value set by the script, or additional values _added to_ via `RSH_EXTRA_OPTS`
    - this would allow you to do `RSH_EXTRA_OPTS='-c aes128-ctr -o Compression=no'` from above
- BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK & BORG_RELOCATED_REPO_ACCESS_IS_OK env var values can now be defined, but they still default to `no`

Let me know whether this covers your usage needs.

**Comment by sertys3** [comment]
Greetings @laur89 ,
thank you for the work you are putting here. I have pulled the latest image off docker hub and it works as specified and expected.

Off-topic (this possibly is another issue request):
I had one more hick-up during testing which is related to borg locks. A stale lock would break future backups until manually broken. Yet a repository with several upstreams might hold a valid lock in case another host is pushing it's backup.  I have scripted a retry mechanism with borg break-lock command for that in my non-docker setup. I remember the image had a scripting mechanism with run-parts for that? How does one go into implementing such a safeguard with run-backup.sh?

Kind regards,
Daniel

**Comment by laur89** [comment]
> A stale lock would break future backups until manually broken. Yet a repository with several upstreams might hold a valid lock in case another host is pushing it's backup

If it's a valid lock, i.e. some host is working against a repo, then why would it break future backups? Breakage could only happen if said process doesn't release lock on completion.

If the locks are valid and held by different machines, then think you should use `--lock-wait` option (note it's borg's [native option](https://borgbackup.readthedocs.io/en/stable/usage/general.html#common-options)) with a sufficiently large value. In case the locks are broken, it sounds like there are bigger problems that need addressing.

> I remember the image had a scripting mechanism with run-parts for that?

Nah, that's an undocumented feature allowing running extra commands at different steps of the backup lifecycle. Lock-breaking logic could be injected by it, but I'd be extremely careful when messing with the locks.

---

As a side-note, you might want to consider [duplicacy](https://github.com/gilbertchen/duplicacy), as it handles backups without any locks whatsoever. Were I to set up new backup today, I'd choose this. But as I've used borg for nearly a decade now and it fulfills my use-case, I can't be bothered to migrate away.

**Comment by laur89** [comment]
Closing. Feel free to reopen if unsolved.
